name: AWS example workflow

on:
  push:

env:
  BUCKET_NAME: "nishad-demo-bucket01"
  AWS_REGION: "us-east-1"

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for checkout

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: oidc-github-role
          aws-region: ${{ env.AWS_REGION }}

      - name: List buckets
        run: aws s3 ls
