name: Github AWS OIDC

on:
  push:
    branches: [main]

permissions:
  id-token: write   # required for OIDC
  contents: read    # required for actions/checkout

jobs:
  oidc-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: oidc-github-role
          aws-region: us-east-1

      - name: Test AWS credentials
        run: aws sts get-caller-identity
